### ISSUE TITLE
Sprint Monday 26 / 8

### ISSUE THREAD

**Issue by wach0001** [Mercantec-GHC/h2-projekt-maws-hotel#13]
- [x] Sebastian - User / Login / JWT 
- [x] Walid - Undersøg om du kan implementere en connection string fra neon til dit EFC projekt
- [x] Abdi - Basic User Story 
- [x] Malthe - Welcome page / Nav etc etc

**Comment by AssisDk** [comment]
Basic User Story
[Basic user story - Sprint .docx](https://github.com/user-attachments/files/16796659/Basic.user.story.-.Sprint.docx)

**Comment by wach0001** [comment]
![image](https://github.com/user-attachments/assets/61476bc2-858f-4a9b-bbdb-9f219be71949)
