### ISSUE TITLE
Sprint Weds 28 / 8

### ISSUE THREAD

**Issue by wach0001** [Mercantec-GHC/h2-projekt-maws-hotel#14]
- [x] Sebastian - User / Login / JWT 
- [x] Walid - Uploader min resp så andre kan se den
- [x] Abdi - lav en prioritering over hvad vi skal kigge på først i forhold til gennemførelse af vores projekt
- [x] Malthe - Mere Welcome - kigger Walids resp

**Comment by AssisDk** [comment]
prioriteringsliste 
[Prioriterings liste - Maws hotel .docx](https://github.com/user-attachments/files/16796694/Prioriterings.liste.-.Maws.hotel.docx)

**Comment by wach0001** [comment]
![image](https://github.com/user-attachments/assets/f26aee44-ce77-4c77-ae61-48d5e91beed8)
