### ISSUE TITLE
Sprint Thursday 28-08

### ISSUE THREAD

**Issue by wach0001** [Mercantec-GHC/h2-projekt-maws-hotel#15]
- [x] Sebastian - Leg lidt rundt med Walids projekt for at få en bedre forståelse af hvordan EFC fungerer.
- [x] Abdi - Begynd at arbejde på en af dine top 3 i listen af prio
- [x] Walid - Jeg merger mit projekt sammen med holdets projekt, evt lave alle classes
- [x] Malthe - Lav en sammenlign med EFC og anden database metode, og find ud af hvilken vil give mindst hovedpine

**Comment by AssisDk** [comment]
[Selvvalgt udefra Prioriteter - Maws Hotel.docx](https://github.com/user-attachments/files/16796700/Selvvalgt.udefra.Prioriteter.-.Maws.Hotel.docx)

**Comment by wach0001** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:////Users/walidchan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

<link rel=themeData
href="file:////Users/walidchan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:////Users/walidchan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=en-DK style='tab-interval:36.0pt;word-wrap:break-word'>


<p class=MsoNormal><b><span lang=DA>Prisoversigt for Værelseskategorier<o:p></o:p></span></b></p>


Værelseskategori | Beskrivelse | Pris per nat (DKK)
-- | -- | --
Standard | Enkeltværelse med grundlæggende faciliteter. | 700 kr
Komfort | Dobbeltværelse med ekstra plads og komfort. | 900 kr
Superior | Værelse med udsigt, større opholdsrum. | 1200 kr
Deluxe | Luksuriøst værelse med premium faciliteter. | 1500 kr
Suite | Stort værelse med separat stue og   soveværelse. | 2000 kr



<p class=MsoNormal><span lang=DA><o:p>&nbsp;</o:p></span></p>


</body>

</html>
